# Generated by Django 4.2.6 on 2023-11-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reading_time',
        ),
    ]
