# Generated by Django 4.2.6 on 2023-11-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_remove_post_reading_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='social_app__publish_50c2cd_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created'], name='social_app__created_b8a1df_idx'),
        ),
    ]
