# Generated by Django 4.2.6 on 2023-11-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='discription',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
