# Generated by Django 4.2.6 on 2023-11-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_rename_caption_post_discription_remove_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.CharField(max_length=1000),
        ),
    ]
