# Generated by Django 4.2.6 on 2023-11-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.TextField(max_length=1000),
        ),
    ]
