# Generated by Django 4.2.6 on 2023-11-05 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_alter_comments_active_postsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postsimage',
            name='image',
            field=models.ImageField(upload_to='posts-image/'),
        ),
    ]
