# Generated by Django 4.2.6 on 2023-11-08 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0012_post_likes_alter_postsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='post_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
