# Generated by Django 4.2.6 on 2023-11-09 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0014_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='social_app.Following', to=settings.AUTH_USER_MODEL),
        ),
    ]
